_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 86
                - 95
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 86
                - 95
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.10.4
            "5": 0.18.7
            "6": 4.47.0.dev0
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
chunk_overlap:
    value: 100
chunk_size:
    value: 500
embed_model_name:
    value: all-MiniLM-L6-v2
llm_model_name:
    value: mistralai/Mistral-7B-Instruct-v0.3
top_k:
    value: 5
